# 生产环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: QWer!@34

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #        cluster-name: BJ

    sentinel:
      #      filter:
      #        # 关闭对spring mvc端点的保护
      #        enabled: false
      transport:
        # 指定sentinel控制台的地址
        dashboard: localhost:8090
        client-ip: 10.0.8.2
        port: 8720
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group

      bindings:
        output:
          # 用来指定topic
          destination: add-bonus
        my-output:
          destination: stream-my-topic
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.tsien.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  # 让feign使用apache httpclient 做请求，而不是urlconnection
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

jwt:
  secret: aaabbbcccdddeeeaaabbbcccdddeeeaaabbbcccdddeeeaaabbbcccdddeeeaaabbbcccdddeeeaaabbbcccdddeee
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

logging:
  level:
    com.tsien: debug
#    com.tsien.contentcenter.feignclient.UserCenterFeignClient: debug


server:
  port: 8012