spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 18896727773
  cloud:
    nacos:
      discovery:
        server-addr: 81.68.78.224:8848
        #        cluster-name: BJ
    sentinel:
#      filter:
#        # 关闭对spring mvc端点的保护
#        enabled: false
      transport:
        # 指定sentinel控制台的地址
        dashboard: localhost:8080
        port: 8720
  application:
    name: content-center

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: 8010

#配置文件方式配置Ribbon
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置Ribbon饥饿加载，解决第一次请求过慢的问题，多个的话逗号分隔
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.tsien: debug
#    com.tsien.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: basic
  # 让feign使用apache httpclient 做请求，而不是urlconnection
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'



