# 生产环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.2.5:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: QWer!@34

  cloud:
    nacos:
      discovery:
        server-addr: 10.0.2.5:8848
        #        cluster-name: BJ

    sentinel:
      #      filter:
      #        # 关闭对spring mvc端点的保护
      #        enabled: false
      transport:
        # 指定sentinel控制台的地址
        dashboard: 10.0.2.5:8090
        client-ip: 10.0.2.10
        port: 8720

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: basic
  # 让feign使用apache httpclient 做请求，而不是urlconnection
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

logging:
  level:
    com.tsien: debug
#    com.tsien.contentcenter.feignclient.UserCenterFeignClient: debug

server:
  port: 8012