spring:
  profiles:
    active: dev

  application:
    name: content-center

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#配置文件方式配置Ribbon
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置Ribbon饥饿加载，解决第一次请求过慢的问题，多个的话逗号分隔
ribbon:
  eager-load:
    enabled: true
    clients: user-center


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always